// =====================================================
// DATA PERPUSTAKAAN MTsN 7 BANJAR
// =====================================================

const LIBRARY_STATS = {
  // totalBuku: 847,
  // bukuTerbaca: 4231,
  // anggota: 389,
  // kategori: 18,
};

const PAKET_DATA = [
  {
    id: "kelas-7",
    name: "Kelas 7",
    level: "Tingkat Pertama",
    description: "Koleksi buku pelajaran umum dan agama untuk siswa kelas 7 MTsN 7 Banjar",
    gradient: "linear-gradient(135deg,#38bdf8,#3b82f6)",
    emoji: "📘",
    bookCount: 132,
  },
  {
    id: "kelas-8",
    name: "Kelas 8",
    level: "Tingkat Menengah",
    description: "Koleksi buku pelajaran umum dan agama untuk siswa kelas 8 MTsN 7 Banjar",
    gradient: "linear-gradient(135deg,#a78bfa,#a855f7)",
    emoji: "📗",
    bookCount: 145,
  },
  {
    id: "kelas-9",
    name: "Kelas 9",
    level: "Tingkat Akhir",
    description: "Koleksi buku pelajaran umum dan agama untuk siswa kelas 9 MTsN 7 Banjar",
    gradient: "linear-gradient(135deg,#fb7185,#ec4899)",
    emoji: "📕",
    bookCount: 128,
  },
];

const SUBJECTS_BY_PAKET = {
  "kelas-7": [
    { id: "bahasa-indonesia", name: "Bahasa Indonesia", icon: "📖" },
    { id: "matematika", name: "Matematika", icon: "🔢" },
    { id: "ipa", name: "IPA", icon: "🔬" },
    { id: "ips", name: "IPS", icon: "🌍" },
    { id: "bahasa-inggris", name: "Bahasa Inggris", icon: "🌐" },
    { id: "pkn", name: "PKn", icon: "🏛️" },
    { id: "alquran-hadits", name: "Al-Qur'an Hadits", icon: "📿" },
    { id: "aqidah-akhlak", name: "Aqidah Akhlak", icon: "🌙" },
    { id: "fiqih", name: "Fiqih", icon: "☪️" },
    { id: "ski", name: "SKI", icon: "📜" },
    { id: "bahasa-arab", name: "Bahasa Arab", icon: "🕌" },
    { id: "prakarya", name: "Prakarya", icon: "🛠️" },
    { id: "pjok", name: "PJOK", icon: "⚽" },
    { id: "TIK", name: "Informatika/TIK", icon: "💻" },

  ],
  "kelas-8": [
    { id: "bahasa-indonesia", name: "Bahasa Indonesia", icon: "📖" },
    { id: "matematika", name: "Matematika", icon: "🔢" },
    { id: "ipa", name: "IPA", icon: "🔬" },
    { id: "ips", name: "IPS", icon: "🌍" },
    { id: "bahasa-inggris", name: "Bahasa Inggris", icon: "🌐" },
    { id: "pkn", name: "PKn", icon: "🏛️" },
    { id: "alquran-hadits", name: "Al-Qur'an Hadits", icon: "📿" },
    { id: "aqidah-akhlak", name: "Aqidah Akhlak", icon: "🌙" },
    { id: "fiqih", name: "Fiqih", icon: "☪️" },
    { id: "ski", name: "SKI", icon: "📜" },
    { id: "bahasa-arab", name: "Bahasa Arab", icon: "🕌" },
    { id: "prakarya", name: "Prakarya", icon: "🛠️" },
    { id: "pjok", name: "PJOK", icon: "⚽" },
    { id: "TIK", name: "Informatika/TIK", icon: "💻" },

  ],
  "kelas-9": [
    { id: "bahasa-indonesia", name: "Bahasa Indonesia", icon: "📖" },
    { id: "matematika", name: "Matematika", icon: "🔢" },
    { id: "ipa", name: "IPA", icon: "🔬" },
    { id: "ips", name: "IPS", icon: "🌍" },
    { id: "bahasa-inggris", name: "Bahasa Inggris", icon: "🌐" },
    { id: "pkn", name: "PKn", icon: "🏛️" },
    { id: "alquran-hadits", name: "Al-Qur'an Hadits", icon: "📿" },
    { id: "aqidah-akhlak", name: "Aqidah Akhlak", icon: "🌙" },
    { id: "fiqih", name: "Fiqih", icon: "☪️" },
    { id: "ski", name: "SKI", icon: "📜" },
    { id: "bahasa-arab", name: "Bahasa Arab", icon: "🕌" },
    { id: "prakarya", name: "Prakarya", icon: "🛠️" },
    { id: "pjok", name: "PJOK", icon: "⚽" },
    { id: "TIK", name: "Informatika/TIK", icon: "💻" },    
  ],
};

const BOOKS_DATA = [
// ===== KELAS 7 (REVISI SESUAI DATA) =====
  { 
    id: "b001", 
    title: "Bahasa Indonesia Kelas VII (Revisi)", 
    author: "Eugenia Rakhma, dkk", 
    paket: "kelas-7", 
    mapel: "bahasa-indonesia", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Bahasa_Indonesia_BS_KLS_VII_Rev.pdf",
    description: "Buku teks Bahasa Indonesia utama untuk mendukung proses pembelajaran kurikulum merdeka.", 
    pages: 280, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#60a5fa,#7dd3fc)", 
    emoji: "📖", 
    publisher: "Pusat Kurikulum dan Perbukuan", 
    edition: "Edisi Revisi",
    isbn: "978-623-118-368-2"
  },
  { 
    id: "b002", 
    title: "Pendidikan Pancasila Kelas VII", 
    author: "Yayat Suryatna, dkk", 
    paket: "kelas-7", 
    mapel: "pkn", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Pendidikan-Pancasila-BS-KLS-VII.pdf",
    description: "Membahas nilai-nilai luhur Pancasila dan penerapannya dalam kehidupan sehari-hari.", 
    pages: 210, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#f87171,#fca5a5)", 
    emoji: "🏛️", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-194-633-1"
  },
  { 
    id: "b003", 
    title: "Matematika Kelas VII", 
    author: "Dicky Susanto, dkk", 
    paket: "kelas-7", 
    mapel: "matematika", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Matematika-BS-KLS-VII.pdf",
    description: "Konsep dasar matematika mulai dari bilangan, aljabar, hingga statistika untuk tingkat MTs.", 
    pages: 320, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#c084fc,#c4b5fd)", 
    emoji: "🔢", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-602-244-883-9"
  },
  { 
    id: "b004", 
    title: "Ilmu Pengetahuan Alam Kelas VII (Revisi)", 
    author: "Victoriani Inabuy, dkk", 
    paket: "kelas-7", 
    mapel: "ipa", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPA_BS_KLS_VII_Rev.pdf",
    description: "Menjelajahi fenomena alam, klasifikasi makhluk hidup, dan ekosistem.", 
    pages: 350, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#34d399,#5eead4)", 
    emoji: "🔬", 
    publisher: "Pusat Kurikulum dan Perbukuan", 
    edition: "Edisi Revisi",
    isbn: "978-623-118-457-3"
  },
  { 
    id: "b005", 
    title: "Ilmu Pengetahuan Sosial Kelas VII (Revisi)", 
    author: "Muhammad Nursaban, Supardi", 
    paket: "kelas-7", 
    mapel: "ips", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPS_BS_KLS_VII_Rev.pdf",
    description: "Mempelajari interaksi manusia dengan ruang, waktu, dan dinamika sosial masyarakat.", 
    pages: 310, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#fbbf24,#fde047)", 
    emoji: "🌍", 
    publisher: "Pusat Kurikulum dan Perbukuan", 
    edition: "Edisi Revisi",
    isbn: "978-623-118-437-5"
  },
  { 
    id: "b006", 
    title: "PJOK Kelas VII", 
    author: "Ebta Heri S, Muhajir", 
    paket: "kelas-7", 
    mapel: "pjok", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/PJOK_BS_KLS_VII.pdf",
    description: "Panduan aktivitas jasmani, olahraga berkelompok, dan pemahaman kesehatan diri.", 
    pages: 250, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#f472b6,#fda4af)", 
    emoji: "⚽", 
    publisher: "Pusat Kurikulum dan Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-388-727-4"
  },
  { 
    id: "b007", 
    title: "Koding dan Kecerdasan Artifisial VII", 
    author: "Indra Budi Aji, dkk", 
    paket: "kelas-7", 
    mapel: "TIK", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/KKA_BS_KLS_7.pdf",
    description: "Mempelajari logika pemrograman koding dan pengenalan kecerdasan buatan sejak dini.", 
    pages: 180, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#6366f1,#818cf8)", 
    emoji: "💻", 
    publisher: "Pusat Perbukuan", 
    edition: "Edisi Pertama",
    isbn: "978-634-00-2043-4"
  },

// ===== KELAS 8 (REVISI SESUAI DATA) =====
  { 
    id: "b011", 
    title: "Pendidikan Pancasila Kelas VIII", 
    author: "Tudi Setiawan, dkk", 
    paket: "kelas-8", 
    mapel: "pkn", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Pendidikan-Pancasila-BS-KLS-VIII.pdf",
    description: "Mempelajari kedudukan dan fungsi Pancasila serta konstitusi dalam kehidupan berbangsa.", 
    pages: 200, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#ef4444,#f87171)", 
    emoji: "🏛️", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-194-634-8"
  },
  { 
    id: "b012", 
    title: "Bahasa Indonesia Kelas VIII (Revisi)", 
    author: "Elly Delfia, Maya Lestari G.", 
    paket: "kelas-8", 
    mapel: "bahasa-indonesia", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Indonesia_BS_KLS_VIII_Rev.pdf",
    description: "Edisi revisi yang mencakup penulisan teks laporan, iklan, dan artikel ilmiah populer.", 
    pages: 295, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#3b82f6,#60a5fa)", 
    emoji: "📝", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-388-142-5"
  },
  { 
    id: "b013", 
    title: "Matematika Kelas VIII", 
    author: "Mohammad Tohir, dkk", 
    paket: "kelas-8", 
    mapel: "matematika", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Matematika-BS-KLS-VIII-Baru.pdf",
    description: "Membahas teori Pythagoras, persamaan linear dua variabel, dan geometri tingkat menengah.", 
    pages: 340, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#8b5cf6,#a78bfa)", 
    emoji: "📐", 
    publisher: "Kemdikbudristek", 
    edition: "Cetakan Ke-1",
    isbn: "978-602-427-919-6"
  },
  { 
    id: "b014", 
    title: "Ilmu Pengetahuan Alam Kelas VIII (Revisi)", 
    author: "Okky Fajar T.M., dkk", 
    paket: "kelas-8", 
    mapel: "ipa", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPA_BS_KLS_VIII_Rev.pdf",
    description: "Menjelajahi struktur tubuh manusia, unsur kimia dasar, dan getaran/gelombang.", 
    pages: 370, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#10b981,#34d399)", 
    emoji: "⚗️", 
    publisher: "Pusat Kurikulum dan Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-388-560-7"
  },
  { 
    id: "b015", 
    title: "Ilmu Pengetahuan Sosial Kelas VIII (Revisi)", 
    author: "Supardi, dkk", 
    paket: "kelas-8", 
    mapel: "ips", 
    link: "https://files.cloudapp.web.id/buku/BukuPendidikan/IPS_BS_KLS_VIII_Rev.pdf",
    description: "Mempelajari keragaman alam, sumber daya ekonomi, dan dinamika penduduk Indonesia.", 
    pages: 325, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#f59e0b,#fbbf24)", 
    emoji: "🗺️", 
    publisher: "Pusat Perbukuan", 
    edition: "Edisi Revisi",
    isbn: "978-634-00-0085-6"
  },
  { 
    id: "b016", 
    title: "PJOK Kelas VIII", 
    author: "Yusnita P., Ebta Heri S.", 
    paket: "kelas-8", 
    mapel: "pjok", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/PJOK_BS_KLS_VIII.pdf",
    description: "Materi aktivitas olahraga air, senam lantai, dan pola hidup sehat bagi remaja.", 
    pages: 260, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#ec4899,#f472b6)", 
    emoji: "🏀", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-388-721-2"
  },

// ===== KELAS 9 (REVISI SESUAI DATA) =====
  { 
    id: "b021", 
    title: "Pendidikan Pancasila Kelas IX", 
    author: "Khoiriyaningsih, dkk", 
    paket: "kelas-9", 
    mapel: "pkn", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Pendidikan-Pancasila-BS-KLS-IX.pdf",
    description: "Membahas tentang kedaulatan negara, hak asasi manusia, dan peran Indonesia dalam tata dunia global.", 
    pages: 220, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#991b1b,#dc2626)", 
    emoji: "🏛️", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-194-635-5"
  },
  { 
    id: "b022", 
    title: "Bahasa Indonesia Kelas IX", 
    author: "Eva Y. Nukman, dkk", 
    paket: "kelas-9", 
    mapel: "bahasa-indonesia", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Bahasa-Indonesia-BS-KLS-IX.pdf",
    description: "Fokus pada teks diskusi, narasi kreatif, dan literasi kritis untuk persiapan jenjang berikutnya.", 
    pages: 280, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#1e40af,#3b82f6)", 
    emoji: "📰", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-602-244-636-1"
  },
  { 
    id: "b023", 
    title: "Matematika Kelas IX", 
    author: "Yosep Dwi Kristanto, dkk", 
    paket: "kelas-9", 
    mapel: "matematika", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Matematika_BS_KLS_IX.pdf",
    description: "Mempelajari perpangkatan, fungsi kuadrat, transformasi, dan geometri bola.", 
    pages: 360, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#6d28d9,#8b5cf6)", 
    emoji: "📊", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-602-427-918-9"
  },
  { 
    id: "b024", 
    title: "IPA Kelas IX (Edisi Revisi)", 
    author: "Cece Sutia, dkk", 
    paket: "kelas-9", 
    mapel: "ipa", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPA_BS_KLS_IX_Rev.pdf",
    description: "Membahas sistem reproduksi, genetika, listrik statis/dinamis, dan teknologi ramah lingkungan.", 
    pages: 385, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#065f46,#10b981)", 
    emoji: "🌿", 
    publisher: "Pusat Perbukuan", 
    edition: "Edisi Revisi",
    isbn: "978-634-00-2430-2"
  },
  { 
    id: "b025", 
    title: "IPS Kelas IX", 
    author: "Mohammad Rizky S, dkk", 
    paket: "kelas-9", 
    mapel: "ips", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPS-BS-KLS-IX.pdf",
    description: "Mempelajari globalisasi, perdagangan internasional, dan sejarah perjuangan bangsa.", 
    pages: 330, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#92400e,#f59e0b)", 
    emoji: "🌏", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-602-244-469-5"
  },
];

const STORY_BOOKS_DATA = [
 { 
    id: "s001", 
    title: "Si Kancil dan Buaya", 
    author: "Tim Nusantara", 
    link: "https://literacycloud.org/stories/300-the-mouse-deer-and-the-crocodiles/", // Contoh link baca online
    ageGroup: "5-8 tahun", 
    description: "Kisah klasik si kancil yang cerdik berhasil menyeberangi sungai dengan tipu muslihatnya.", 
    gradient: "linear-gradient(135deg,#4ade80,#6ee7b7)", 
    emoji: "🦊", 
    pages: 24 
  },
  { id: "s002", title: "Petualangan Budi ke Bulan", author: "Sari Dewi", ageGroup: "6-10 tahun", description: "Budi bermimpi pergi ke bulan dan bertemu dengan makhluk-makhluk luar angkasa yang lucu.", gradient: "linear-gradient(135deg,#60a5fa,#a5b4fc)", emoji: "🚀", pages: 64 },
  { id: "s003", title: "Malin Kundang", author: "Legenda Minangkabau", ageGroup: "8-12 tahun", description: "Kisah anak durhaka yang dikutuk menjadi batu oleh ibunya yang ia telantarkan.", gradient: "linear-gradient(135deg,#fbbf24,#fdba74)", emoji: "🌊", pages: 56 },
  { id: "s004", title: "Putri Salju Nusantara", author: "Rima Anggraini", ageGroup: "5-9 tahun", description: "Kisah putri cantik yang melarikan diri ke hutan dan tinggal bersama tujuh kurcaci.", gradient: "linear-gradient(135deg,#f472b6,#fda4af)", emoji: "👸", pages: 72 },
  { id: "s005", title: "Garuda dan Naga Sakti", author: "Adi Prawoto", ageGroup: "8-13 tahun", description: "Pertarungan epik Garuda melawan Naga Sakti untuk membebaskan sang ibu.", gradient: "linear-gradient(135deg,#f87171,#fdba74)", emoji: "🦅", pages: 88 },
  { id: "s006", title: "Kisah Negeri Donat", author: "Luna Pratiwi", ageGroup: "4-7 tahun", description: "Imajinasi luar biasa tentang negeri ajaib yang terbuat dari makanan lezat.", gradient: "linear-gradient(135deg,#facc15,#fcd34d)", emoji: "🍩", pages: 40 },
  { id: "s007", title: "Sang Penjaga Hutan", author: "Bambang Nugroho", ageGroup: "7-12 tahun", description: "Seorang anak yang belajar mencintai alam dan menjaga kelestarian hutan.", gradient: "linear-gradient(135deg,#34d399,#86efac)", emoji: "🌳", pages: 80 },
  { id: "s008", title: "Anak Rajin dan Lampu Ajaib", author: "Tim Pustaka Anak", ageGroup: "6-9 tahun", description: "Kisah anak rajin yang menemukan lampu ajaib dan belajar tentang tanggung jawab.", gradient: "linear-gradient(135deg,#a78bfa,#d8b4fe)", emoji: "🪔", pages: 52 },
  { id: "s009", title: "Bima Si Kupu-kupu Biru", author: "Anisa Harahap", ageGroup: "4-6 tahun", description: "Petualangan kupu-kupu kecil berwarna biru yang mencari teman di taman bunga.", gradient: "linear-gradient(135deg,#38bdf8,#67e8f9)", emoji: "🦋", pages: 36 },
  { id: "s010", title: "Legenda Danau Toba", author: "Cerita Rakyat Sumatera", ageGroup: "9-13 tahun", description: "Kisah asal-usul Danau Toba yang penuh dengan nilai-nilai budaya Batak.", gradient: "linear-gradient(135deg,#2dd4bf,#7dd3fc)", emoji: "🏞️", pages: 68 },
  { 
    id: "s011", 
    title: "Asal Usul Sungai Barito", 
    author: "Cerita Rakyat Kalimantan", 
    link: "https://buku.kemdikbud.go.id/katalog/asal-usul-sungai-barito", // Link info buku kemdikbud
    ageGroup: "6-10 tahun", 
    description: "Legenda asal-usul Sungai Barito yang penuh nilai-nilai budaya Banjar yang kaya.", 
    gradient: "linear-gradient(135deg,#94a3b8,#93c5fd)", 
    emoji: "🌊", 
    pages: 32 
  },
  { 
    id: "s012", 
    title: "Demang Lehman Pahlawan Banjar", 
    author: "Literasi Kalsel", 
    link: "https://repositori.kemdikbud.go.id/11438/1/Demang%20Lehman.pdf", // Link PDF langsung
    ageGroup: "9-13 tahun", 
    description: "Kisah keberanian Demang Lehman, pahlawan dari Kalimantan Selatan yang membela tanah air.", 
    gradient: "linear-gradient(135deg,#ef4444,#fb7185)", 
    emoji: "⚔️", 
    pages: 45 
  }
];
