// =====================================================
// DATA PERPUSTAKAAN MTsN 7 BANJAR
// =====================================================

const LIBRARY_STATS = {
  // totalBuku: 847,
  // bukuTerbaca: 4231,
  // anggota: 389,
  // kategori: 18,
};

const PAKET_DATA = [
  {
    id: "kelas-7",
    name: "Kelas 7",
    level: "Tingkat Pertama",
    description: "Koleksi buku pelajaran umum dan agama untuk siswa kelas 7 MTsN 7 Banjar",
    gradient: "linear-gradient(135deg,#38bdf8,#3b82f6)",
    emoji: "📘",
    bookCount: 132,
  },
  {
    id: "kelas-8",
    name: "Kelas 8",
    level: "Tingkat Menengah",
    description: "Koleksi buku pelajaran umum dan agama untuk siswa kelas 8 MTsN 7 Banjar",
    gradient: "linear-gradient(135deg,#a78bfa,#a855f7)",
    emoji: "📗",
    bookCount: 145,
  },
  {
    id: "kelas-9",
    name: "Kelas 9",
    level: "Tingkat Akhir",
    description: "Koleksi buku pelajaran umum dan agama untuk siswa kelas 9 MTsN 7 Banjar",
    gradient: "linear-gradient(135deg,#fb7185,#ec4899)",
    emoji: "📕",
    bookCount: 128,
  },
];

const SUBJECTS_BY_PAKET = {
  "kelas-7": [
    { id: "bahasa-indonesia", name: "Bahasa Indonesia", icon: "📖" },
    { id: "matematika", name: "Matematika", icon: "🔢" },
    { id: "ipa", name: "IPA", icon: "🔬" },
    { id: "ips", name: "IPS", icon: "🌍" },
    { id: "bahasa-inggris", name: "Bahasa Inggris", icon: "🌐" },
    { id: "pkn", name: "PKn", icon: "🏛️" },
    { id: "alquran-hadits", name: "Al-Qur'an Hadits", icon: "📿" },
    { id: "aqidah-akhlak", name: "Aqidah Akhlak", icon: "🌙" },
    { id: "fiqih", name: "Fiqih", icon: "☪️" },
    { id: "ski", name: "SKI", icon: "📜" },
    { id: "bahasa-arab", name: "Bahasa Arab", icon: "🕌" },
    { id: "prakarya", name: "Prakarya", icon: "🛠️" },
    { id: "pjok", name: "PJOK", icon: "⚽" },
    { id: "TIK", name: "Informatika/TIK", icon: "💻" },

  ],
  "kelas-8": [
    { id: "bahasa-indonesia", name: "Bahasa Indonesia", icon: "📖" },
    { id: "matematika", name: "Matematika", icon: "🔢" },
    { id: "ipa", name: "IPA", icon: "🔬" },
    { id: "ips", name: "IPS", icon: "🌍" },
    { id: "bahasa-inggris", name: "Bahasa Inggris", icon: "🌐" },
    { id: "pkn", name: "PKn", icon: "🏛️" },
    { id: "alquran-hadits", name: "Al-Qur'an Hadits", icon: "📿" },
    { id: "aqidah-akhlak", name: "Aqidah Akhlak", icon: "🌙" },
    { id: "fiqih", name: "Fiqih", icon: "☪️" },
    { id: "ski", name: "SKI", icon: "📜" },
    { id: "bahasa-arab", name: "Bahasa Arab", icon: "🕌" },
    { id: "prakarya", name: "Prakarya", icon: "🛠️" },
    { id: "pjok", name: "PJOK", icon: "⚽" },
    { id: "TIK", name: "Informatika/TIK", icon: "💻" },

  ],
  "kelas-9": [
    { id: "bahasa-indonesia", name: "Bahasa Indonesia", icon: "📖" },
    { id: "matematika", name: "Matematika", icon: "🔢" },
    { id: "ipa", name: "IPA", icon: "🔬" },
    { id: "ips", name: "IPS", icon: "🌍" },
    { id: "bahasa-inggris", name: "Bahasa Inggris", icon: "🌐" },
    { id: "pkn", name: "PKn", icon: "🏛️" },
    { id: "alquran-hadits", name: "Al-Qur'an Hadits", icon: "📿" },
    { id: "aqidah-akhlak", name: "Aqidah Akhlak", icon: "🌙" },
    { id: "fiqih", name: "Fiqih", icon: "☪️" },
    { id: "ski", name: "SKI", icon: "📜" },
    { id: "bahasa-arab", name: "Bahasa Arab", icon: "🕌" },
    { id: "prakarya", name: "Prakarya", icon: "🛠️" },
    { id: "pjok", name: "PJOK", icon: "⚽" },
    { id: "TIK", name: "Informatika/TIK", icon: "💻" },    
  ],
};

const BOOKS_DATA = [
// ===== KELAS 7 (REVISI SESUAI DATA) =====
  { 
    id: "b001", 
    title: "Bahasa Indonesia Kelas VII (Revisi)", 
    author: "Eugenia Rakhma, dkk", 
    paket: "kelas-7", 
    mapel: "bahasa-indonesia", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Bahasa_Indonesia_BS_KLS_VII_Rev.pdf",
    description: "Buku teks Bahasa Indonesia utama untuk mendukung proses pembelajaran kurikulum merdeka.", 
    pages: 280, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#60a5fa,#7dd3fc)", 
    emoji: "📖", 
    publisher: "Pusat Kurikulum dan Perbukuan", 
    edition: "Edisi Revisi",
    isbn: "978-623-118-368-2"
  },
  { 
    id: "b002", 
    title: "Pendidikan Pancasila Kelas VII", 
    author: "Yayat Suryatna, dkk", 
    paket: "kelas-7", 
    mapel: "pkn", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Pendidikan-Pancasila-BS-KLS-VII.pdf",
    description: "Membahas nilai-nilai luhur Pancasila dan penerapannya dalam kehidupan sehari-hari.", 
    pages: 210, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#f87171,#fca5a5)", 
    emoji: "🏛️", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-194-633-1"
  },
  { 
    id: "b003", 
    title: "Matematika Kelas VII", 
    author: "Dicky Susanto, dkk", 
    paket: "kelas-7", 
    mapel: "matematika", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Matematika-BS-KLS-VII.pdf",
    description: "Konsep dasar matematika mulai dari bilangan, aljabar, hingga statistika untuk tingkat MTs.", 
    pages: 320, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#c084fc,#c4b5fd)", 
    emoji: "🔢", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-602-244-883-9"
  },
  { 
    id: "b004", 
    title: "Ilmu Pengetahuan Alam Kelas VII (Revisi)", 
    author: "Victoriani Inabuy, dkk", 
    paket: "kelas-7", 
    mapel: "ipa", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPA_BS_KLS_VII_Rev.pdf",
    description: "Menjelajahi fenomena alam, klasifikasi makhluk hidup, dan ekosistem.", 
    pages: 350, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#34d399,#5eead4)", 
    emoji: "🔬", 
    publisher: "Pusat Kurikulum dan Perbukuan", 
    edition: "Edisi Revisi",
    isbn: "978-623-118-457-3"
  },
  { 
    id: "b005", 
    title: "Ilmu Pengetahuan Sosial Kelas VII (Revisi)", 
    author: "Muhammad Nursaban, Supardi", 
    paket: "kelas-7", 
    mapel: "ips", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPS_BS_KLS_VII_Rev.pdf",
    description: "Mempelajari interaksi manusia dengan ruang, waktu, dan dinamika sosial masyarakat.", 
    pages: 310, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#fbbf24,#fde047)", 
    emoji: "🌍", 
    publisher: "Pusat Kurikulum dan Perbukuan", 
    edition: "Edisi Revisi",
    isbn: "978-623-118-437-5"
  },
  { 
    id: "b006", 
    title: "PJOK Kelas VII", 
    author: "Ebta Heri S, Muhajir", 
    paket: "kelas-7", 
    mapel: "pjok", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/PJOK_BS_KLS_VII.pdf",
    description: "Panduan aktivitas jasmani, olahraga berkelompok, dan pemahaman kesehatan diri.", 
    pages: 250, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#f472b6,#fda4af)", 
    emoji: "⚽", 
    publisher: "Pusat Kurikulum dan Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-388-727-4"
  },
  { 
    id: "b007", 
    title: "Koding dan Kecerdasan Artifisial VII", 
    author: "Indra Budi Aji, dkk", 
    paket: "kelas-7", 
    mapel: "TIK", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/KKA_BS_KLS_7.pdf",
    description: "Mempelajari logika pemrograman koding dan pengenalan kecerdasan buatan sejak dini.", 
    pages: 180, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#6366f1,#818cf8)", 
    emoji: "💻", 
    publisher: "Pusat Perbukuan", 
    edition: "Edisi Pertama",
    isbn: "978-634-00-2043-4"
  },
  { 
    id: "b008", 
    title: "English for Nusantara VII", 
    author: "Ika Lestari Damayanti, dkk", 
    paket: "kelas-7", 
    mapel: "bahasa-inggris", 
    link: "https://drive.google.com/file/d/14SRYenCZOv3RoL7U75IhOsmCbwIvcxJg/view?usp=sharing",
    description: "Buku teks utama Bahasa Inggris untuk siswa SMP/MTs kelas 7 dengan pendekatan kurikulum merdeka.", 
    pages: 250, // Estimasi halaman
    year: 2022, 
    gradient: "linear-gradient(135deg,#3b82f6,#60a5fa)", 
    emoji: "🌐", 
    publisher: "Pusat Perbukuan", 
    edition: "Edisi Pertama",
    isbn: "978-602-244-884-6"
  },
  { 
  id: "m7-aa-7", 
  title: "Akidah Akhlak Kelas VII", 
  author: "Akhmad Fauzi, M.Pd.I", 
  paket: "kelas-7", 
  mapel: "aqidah-akhlak", 
  link: "https://drive.google.com/file/d/1UgaG2DCWOQxR8abIrmo9RB0_fAuVgZsU/view?usp=sharing",
  description: "Membentuk karakter islami melalui pemahaman akidah dan akhlak terpuji.", 
  pages: 180, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#0d9488,#5eead4)", 
  emoji: "🌙", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "m7-ski-7", 
  title: "SKI Kelas VII", 
  author: "Muh. Chamdillah, M.Hum", 
  paket: "kelas-7", 
  mapel: "ski", 
  link: "https://drive.google.com/file/d/1bQMmtFs_ZqtiHPC48nFeovi9oGyYR-4W/view?usp=sharing",
  description: "Menelusuri sejarah perjuangan Nabi Muhammad SAW dan peradaban Islam.", 
  pages: 165, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#7c2d12,#fb923c)", 
  emoji: "📜", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "m7-ba-7", 
  title: "Bahasa Arab Kelas VII", 
  author: "Faruq Baharudin, M.Pd", 
  paket: "kelas-7", 
  mapel: "bahasa-arab", 
  link: "https://drive.google.com/file/d/1Dpn_6dTlK2okiIsJ5V3o90du-K6__q5y/view?usp=sharing",
  description: "Pengenalan dasar komunikasi bahasa Arab untuk lingkungan madrasah.", 
  pages: 190, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#1e3a8a,#60a5fa)", 
  emoji: "🕌", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "m7-qh-7", 
  title: "Al-Qur'an Hadis Kelas VII", 
  author: "Drs. Moh. Hafidz", 
  paket: "kelas-7", 
  mapel: "alquran-hadits", 
  link: "https://drive.google.com/file/d/1GSa3c8BwFhj5XjcQMAd8AMC5GvYlv6Jj/view?usp=sharing",
  description: "Dasar-dasar ilmu Al-Qur'an dan pemahaman hadis pilihan.", 
  pages: 210, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#166534,#4ade80)", 
  emoji: "📿", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "f7-thaharah", 
  title: "Fiqih Thaharah", 
  author: "Ahmad Sarwat, Lc", 
  paket: "kelas-7", 
  mapel: "fiqih", 
  link: "https://drive.google.com/file/d/1M665xdFXm44UTCTFubz0DuB0SGdl6cOQ/view?usp=sharing",
  description: "Membahas hukum bersuci, jenis-jenis air, najis, dan tata cara wudhu sesuai syariat.", 
  pages: 50, 
  year: 2010, 
  gradient: "linear-gradient(135deg,#059669,#34d399)", 
  emoji: "💧", 
  publisher: "DU CENTER PRESS", 
  edition: "Cetakan Pertama",
  isbn: "-"
},
{ 
  id: "f7-shalat", 
  title: "Fiqih Shalat", 
  author: "Ahmad Sarwat, Lc", 
  paket: "kelas-7", 
  mapel: "fiqih", 
  link: "https://drive.google.com/file/d/1gnOj8aJgbENvRLLSFzt-IeLGTlvmSpGj/view?usp=sharing",
  description: "Panduan lengkap shalat fardhu, waktu shalat, syarat sah, rukun, hingga shalat berjamaah.", 
  pages: 115, 
  year: 2010, 
  gradient: "linear-gradient(135deg,#10b981,#6ee7b7)", 
  emoji: "🕌", 
  publisher: "DU CENTER PRESS", 
  edition: "Cetakan Pertama",
  isbn: "-"
},

// ===== KELAS 8 (REVISI SESUAI DATA) =====
  { 
    id: "b011", 
    title: "Pendidikan Pancasila Kelas VIII", 
    author: "Tudi Setiawan, dkk", 
    paket: "kelas-8", 
    mapel: "pkn", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Pendidikan-Pancasila-BS-KLS-VIII.pdf",
    description: "Mempelajari kedudukan dan fungsi Pancasila serta konstitusi dalam kehidupan berbangsa.", 
    pages: 200, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#ef4444,#f87171)", 
    emoji: "🏛️", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-194-634-8"
  },
  { 
    id: "b012", 
    title: "Bahasa Indonesia Kelas VIII (Revisi)", 
    author: "Elly Delfia, Maya Lestari G.", 
    paket: "kelas-8", 
    mapel: "bahasa-indonesia", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Indonesia_BS_KLS_VIII_Rev.pdf",
    description: "Edisi revisi yang mencakup penulisan teks laporan, iklan, dan artikel ilmiah populer.", 
    pages: 295, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#3b82f6,#60a5fa)", 
    emoji: "📝", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-388-142-5"
  },
  { 
    id: "b013", 
    title: "Matematika Kelas VIII", 
    author: "Mohammad Tohir, dkk", 
    paket: "kelas-8", 
    mapel: "matematika", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Matematika-BS-KLS-VIII-Baru.pdf",
    description: "Membahas teori Pythagoras, persamaan linear dua variabel, dan geometri tingkat menengah.", 
    pages: 340, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#8b5cf6,#a78bfa)", 
    emoji: "📐", 
    publisher: "Kemdikbudristek", 
    edition: "Cetakan Ke-1",
    isbn: "978-602-427-919-6"
  },
  { 
    id: "b014", 
    title: "Ilmu Pengetahuan Alam Kelas VIII (Revisi)", 
    author: "Okky Fajar T.M., dkk", 
    paket: "kelas-8", 
    mapel: "ipa", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPA_BS_KLS_VIII_Rev.pdf",
    description: "Menjelajahi struktur tubuh manusia, unsur kimia dasar, dan getaran/gelombang.", 
    pages: 370, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#10b981,#34d399)", 
    emoji: "⚗️", 
    publisher: "Pusat Kurikulum dan Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-388-560-7"
  },
  { 
    id: "b015", 
    title: "Ilmu Pengetahuan Sosial Kelas VIII (Revisi)", 
    author: "Supardi, dkk", 
    paket: "kelas-8", 
    mapel: "ips", 
    link: "https://files.cloudapp.web.id/buku/BukuPendidikan/IPS_BS_KLS_VIII_Rev.pdf",
    description: "Mempelajari keragaman alam, sumber daya ekonomi, dan dinamika penduduk Indonesia.", 
    pages: 325, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#f59e0b,#fbbf24)", 
    emoji: "🗺️", 
    publisher: "Pusat Perbukuan", 
    edition: "Edisi Revisi",
    isbn: "978-634-00-0085-6"
  },
  { 
    id: "b016", 
    title: "PJOK Kelas VIII", 
    author: "Yusnita P., Ebta Heri S.", 
    paket: "kelas-8", 
    mapel: "pjok", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/PJOK_BS_KLS_VIII.pdf",
    description: "Materi aktivitas olahraga air, senam lantai, dan pola hidup sehat bagi remaja.", 
    pages: 260, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#ec4899,#f472b6)", 
    emoji: "🏀", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-388-721-2"
  },
  { 
    id: "b017", 
    title: "English for Nusantara VIII", 
    author: "Ika Lestari Damayanti, dkk", 
    paket: "kelas-8", 
    mapel: "bahasa-inggris", 
    link: "https://drive.google.com/file/d/1t1Ip_QlQ1MwvMQcuRtK2RIQU5X2-JQo-/view?usp=sharing",
    description: "Melanjutkan penguasaan bahasa Inggris melalui tema-tema menarik untuk siswa kelas 8.", 
    pages: 260, // Estimasi halaman
    year: 2022, 
    gradient: "linear-gradient(135deg,#0ea5e9,#38bdf8)", 
    emoji: "🌐", 
    publisher: "Pusat Perbukuan", 
    edition: "Edisi Pertama",
    isbn: "978-602-427-941-7"
  },
  { 
  id: "m8-aa-8", 
  title: "Akidah Akhlak Kelas VIII", 
  author: "Yusuf Hasyim, S.Ag, M.Si", 
  paket: "kelas-8", 
  mapel: "aqidah-akhlak", 
  link: "https://drive.google.com/file/d/1JXx3yBpV6Fidg4DgZMOPfvyoO6y3MKlt/view?usp=sharing",
  description: "Pendalaman materi aqidah Islam dan pembiasaan akhlak mahmudah.", 
  pages: 185, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#0d9488,#5eead4)", 
  emoji: "🌙", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "m8-fiq-8", 
  title: "Fikih Kelas VIII", 
  author: "H. Zainul Ma'arif, MA", 
  paket: "kelas-8", 
  mapel: "fiqih", 
  link: "https://drive.google.com/file/d/10jQyxXkkaCsdnnVTZ5yM8cJezJHpiEES/view?usp=sharing",
  description: "Mempelajari hukum-hukum ibadah dan muamalah dalam Islam.", 
  pages: 200, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#4c1d95,#a78bfa)", 
  emoji: "☪️", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "m8-ski-8", 
  title: "SKI Kelas VIII", 
  author: "Muh. Subhan, M.Hum", 
  paket: "kelas-8", 
  mapel: "ski", 
  link: "https://drive.google.com/file/d/1vE2b80dYIzI6isX2estX2hd8qb9bXtQG/view?usp=sharing",
  description: "Sejarah kekhalifahan Islam dan perkembangan ilmu pengetahuan.", 
  pages: 175, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#7c2d12,#fb923c)", 
  emoji: "📜", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "m8-ba-8", 
  title: "Bahasa Arab Kelas VIII", 
  author: "Masrukhin, S.Pd", 
  paket: "kelas-8", 
  mapel: "bahasa-arab", 
  link: "https://drive.google.com/file/d/1l-bZxwTmvtZyw4LfxeJl8KMy5jBVkE47/view?usp=sharing",
  description: "Peningkatan kemahiran membaca dan berbicara dalam bahasa Arab.", 
  pages: 180, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#1e3a8a,#60a5fa)", 
  emoji: "🕌", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "m8-qh-8", 
  title: "Al-Qur'an Hadis Kelas VIII", 
  author: "Usup Sidik, S.Ag", 
  paket: "kelas-8", 
  mapel: "alquran-hadits", 
  link: "https://drive.google.com/file/d/1Az2wAt2sZgLkFNbs35dI3ad1PQVNNSGf/view?usp=sharing",
  description: "Memahami isi kandungan Al-Qur'an dan fungsi hadis dalam kehidupan.", 
  pages: 195, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#166534,#4ade80)", 
  emoji: "📿", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "f8-infaq", 
  title: "Fiqih Infaq", 
  author: "Tim Redaksi", 
  paket: "kelas-8", 
  mapel: "fiqih", 
  link: "https://drive.google.com/file/d/1ASO51kJe3QLcHkDKvZWbymiWB_EvIDlf/view?usp=sharing",
  description: "Mempelajari hakikat infaq, dalil-dalil landasan, serta perbedaan infaq dengan zakat.", 
  pages: 15, 
  year: 2022, 
  gradient: "linear-gradient(135deg,#047857,#10b981)", 
  emoji: "🪙", 
  publisher: "Penerbit Internal", 
  edition: "Edisi Digital",
  isbn: "-"
},
{ 
  id: "f8-haji", 
  title: "Fiqih Haji", 
  author: "Tim Manasik", 
  paket: "kelas-8", 
  mapel: "fiqih", 
  link: "https://drive.google.com/file/d/1-2scbNyGH8HAfB-Yux9jA4hpiBgj58l6/view?usp=sharing",
  description: "Panduan manasik haji, rukun dan wajib haji, serta alur perjalanan haji Tamattu'.", 
  pages: 25, 
  year: 2023, 
  gradient: "linear-gradient(135deg,#064e3b,#059669)", 
  emoji: "🕋", 
  publisher: "Penerbit Mandiri", 
  edition: "Cetakan Terbaru",
  isbn: "-"
},

// ===== KELAS 9 (REVISI SESUAI DATA) =====
  { 
    id: "b021", 
    title: "Pendidikan Pancasila Kelas IX", 
    author: "Khoiriyaningsih, dkk", 
    paket: "kelas-9", 
    mapel: "pkn", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Pendidikan-Pancasila-BS-KLS-IX.pdf",
    description: "Membahas tentang kedaulatan negara, hak asasi manusia, dan peran Indonesia dalam tata dunia global.", 
    pages: 220, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#991b1b,#dc2626)", 
    emoji: "🏛️", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-623-194-635-5"
  },
  { 
    id: "b022", 
    title: "Bahasa Indonesia Kelas IX", 
    author: "Eva Y. Nukman, dkk", 
    paket: "kelas-9", 
    mapel: "bahasa-indonesia", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Bahasa-Indonesia-BS-KLS-IX.pdf",
    description: "Fokus pada teks diskusi, narasi kreatif, dan literasi kritis untuk persiapan jenjang berikutnya.", 
    pages: 280, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#1e40af,#3b82f6)", 
    emoji: "📰", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-602-244-636-1"
  },
  { 
    id: "b023", 
    title: "Matematika Kelas IX", 
    author: "Yosep Dwi Kristanto, dkk", 
    paket: "kelas-9", 
    mapel: "matematika", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Matematika_BS_KLS_IX.pdf",
    description: "Mempelajari perpangkatan, fungsi kuadrat, transformasi, dan geometri bola.", 
    pages: 360, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#6d28d9,#8b5cf6)", 
    emoji: "📊", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-602-427-918-9"
  },
  { 
    id: "b024", 
    title: "IPA Kelas IX (Edisi Revisi)", 
    author: "Cece Sutia, dkk", 
    paket: "kelas-9", 
    mapel: "ipa", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPA_BS_KLS_IX_Rev.pdf",
    description: "Membahas sistem reproduksi, genetika, listrik statis/dinamis, dan teknologi ramah lingkungan.", 
    pages: 385, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#065f46,#10b981)", 
    emoji: "🌿", 
    publisher: "Pusat Perbukuan", 
    edition: "Edisi Revisi",
    isbn: "978-634-00-2430-2"
  },
  { 
    id: "b025", 
    title: "IPS Kelas IX", 
    author: "Mohammad Rizky S, dkk", 
    paket: "kelas-9", 
    mapel: "ips", 
    link: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPS-BS-KLS-IX.pdf",
    description: "Mempelajari globalisasi, perdagangan internasional, dan sejarah perjuangan bangsa.", 
    pages: 330, 
    year: 2023, 
    gradient: "linear-gradient(135deg,#92400e,#f59e0b)", 
    emoji: "🌏", 
    publisher: "Pusat Perbukuan", 
    edition: "Cetakan Ke-1",
    isbn: "978-602-244-469-5"
  },
  { 
    id: "b026", 
    title: "English for Nusantara IX", 
    author: "Ika Lestari Damayanti, dkk", 
    paket: "kelas-9", 
    mapel: "bahasa-inggris", 
    link: "https://drive.google.com/file/d/1VCPJWoNMqFrMFl0hrFT1F-NZY1CzbwmN/view?usp=sharing",
    description: "Pendalaman materi bahasa Inggris untuk mempersiapkan siswa kelas 9 menuju jenjang berikutnya.", 
    pages: 270, // Estimasi halaman
    year: 2022, 
    gradient: "linear-gradient(135deg,#0284c7,#0ea5e9)", 
    emoji: "🌐", 
    publisher: "Pusat Perbukuan", 
    edition: "Edisi Pertama",
    isbn: "978-602-427-942-4"
  },
  { 
  id: "m9-aa-9", 
  title: "Akidah Akhlak Kelas IX", 
  author: "Hj. Muta'allimah, S.Ag, M.Si", 
  paket: "kelas-9", 
  mapel: "aqidah-akhlak", 
  link: "https://drive.google.com/file/d/1OiOyGu5jsRBCw9zl7QYuvAHz74PRcgF9/view?usp=sharing",
  description: "Mempelajari hari akhir dan etika bermasyarakat secara islami.", 
  pages: 170, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#0d9488,#5eead4)", 
  emoji: "🌙", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "m9-fiq-9", 
  title: "Fikih Kelas IX", 
  author: "Ubaidillah, M.Pd", 
  paket: "kelas-9", 
  mapel: "fiqih", 
  link: "https://drive.google.com/file/d/11_pydyvCgsPNBcxWnrqa27tXiYpRdBxT/view?usp=sharing",
  description: "Pendalaman hukum penyembelihan, kurban, dan ilmu waris dasar.", 
  pages: 220, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#4c1d95,#a78bfa)", 
  emoji: "☪️", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "m9-ski-9", 
  title: "SKI Kelas IX", 
  author: "M. Kholiluddin, M.Pd", 
  paket: "kelas-9", 
  mapel: "ski", 
  link: "https://drive.google.com/file/d/1nMOTqoT7MbhpAJfqLNLQTiMRq9WGRhUa/view?usp=sharing",
  description: "Mempelajari sejarah masuknya Islam di Nusantara dan tradisinya.", 
  pages: 160, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#7c2d12,#fb923c)", 
  emoji: "📜", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "m9-ba-9", 
  title: "Bahasa Arab Kelas IX", 
  author: "Yushi Mukhlisotul, MM", 
  paket: "kelas-9", 
  mapel: "bahasa-arab", 
  link: "https://drive.google.com/file/d/1qoILukC5-6QFQnsDzo1xmgqXO4vwr9WW/view?usp=sharing",
  description: "Kemahiran bahasa Arab tingkat lanjut untuk siswa Madrasah Tsanawiyah.", 
  pages: 185, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#1e3a8a,#60a5fa)", 
  emoji: "🕌", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
  id: "m9-qh-9", 
  title: "Al-Qur'an Hadis Kelas IX", 
  author: "Niswatul Khoiriyah, S.Pd.I, M.Si", 
  paket: "kelas-9", 
  mapel: "alquran-hadits", 
  link: "https://drive.google.com/file/d/1KA3IEnWR3sJl2-AEc97DIDpH4LcjyxG_/",
  description: "Memperdalam pemahaman tajwid dan kandungan hadis tentang lingkungan.", 
  pages: 205, 
  year: 2019, 
  gradient: "linear-gradient(135deg,#166534,#4ade80)", 
  emoji: "📿", 
  publisher: "Direktorat KSKK Madrasah", 
  edition: "KMA 183",
  isbn: "-"
},
{ 
    id: "f9-ijarah", 
    title: "Fiqih Ijarah", 
    author: "Tim Redaksi", 
    paket: "kelas-9", 
    mapel: "fiqih", 
    link: "https://drive.google.com/file/d/1odXCWGdoB1K2RGMBZaKkbBQhzFOO0J2o/view?usp=sharing",
    description: "Membahas akad sewa-menyewa dan upah-mengupah, rukun ijarah, serta hak dan kewajiban dalam akad.", 
    pages: 15, // Estimasi berdasarkan daftar isi
    year: 2024, 
    gradient: "linear-gradient(135deg,#0d9488,#5eead4)", 
    emoji: "🤝", 
    publisher: "Penerbit Internal", 
    edition: "Edisi Digital",
    isbn: "-"
  }
];

const NON_TEXT_BOOKS_DATA = [
  // --- KATEGORI KITAB & WIRID (GURU MUHAMMAD RIJANI) ---
  { 
    id: "nt-ratib-1", 
    title: "Ratib Atthos - Guru Muhammad Rijani", 
    author: "Guru Muhammad Rijani", 
    link: "https://drive.google.com/file/d/13zxZ6HCBJ4VzsT-gz8QBvZJjwxg_CLuH/view?usp=sharing",
    description: "Kumpulan zikir dan doa harian yang disusun oleh Al-Habib Umar bin Abdurrahman Al-Aththas.", 
    gradient: "linear-gradient(135deg,#065f46,#10b981)", 
    emoji: "📿", 
    pages: 32,
    year: 2024
  },
  { 
    id: "nt-ratib-2", 
    title: "Ratib Haddad - Guru Muhammad Rijani", 
    author: "Guru Muhammad Rijani", 
    link: "https://drive.google.com/file/d/1D2O6jaIw20nWT6OReqXpueQVkGliHbX8/view?usp=sharing",
    description: "Zikir Ratib Al-Haddad untuk perlindungan diri dan ketenangan hati.", 
    gradient: "linear-gradient(135deg,#065f46,#10b981)", 
    emoji: "🌙", 
    pages: 40,
    year: 2024
  },
  { 
    id: "nt-wirid-1", 
    title: "Wiridul Latif - Guru Muhammad Rijani", 
    author: "Guru Muhammad Rijani", 
    link: "https://drive.google.com/file/d/1QgMshXMJwXZQhWF8oh9gc8ry8_f5nDTa/view?usp=sharing",
    description: "Wirid pagi dan sore yang disusun oleh Al-Imam Abdullah bin Alwi Al-Haddad.", 
    gradient: "linear-gradient(135deg,#065f46,#10b981)", 
    emoji: "✨", 
    pages: 28,
    year: 2024
  },

  // --- KATEGORI AKIDAH & FIQIH (TAUDHIHUL ADILLAH & LAINNYA) ---
  { 
    id: "nt-sifat-20", 
    title: "Sifat Dua Puluh Awalluddin", 
    author: "Awalluddin", 
    link: "https://drive.google.com/file/d/15bZ4vUhdVnQ_6afn9-13JxNrv85VaXuh/view?usp=sharing",
    description: "Mempelajari dasar-dasar mengenal Allah melalui sifat dua puluh.", 
    gradient: "linear-gradient(135deg,#1e40af,#3b82f6)", 
    emoji: "📖", 
    pages: 120,
    year: 2022
  },
  { 
    id: "nt-taudhih-1", 
    title: "Taudhîhul Adillah Buku 1 (Akidah)", 
    author: "KH. M. Syafi'i Hadzami", 
    link: "https://drive.google.com/file/d/18qhge4jUAQA-tWkLY4pM0DdMK_bpDDY4/view?usp=sharing",
    description: "Penjelasan dalil-dalil agama khusus mengenai persoalan Akidah.", 
    gradient: "linear-gradient(135deg,#334155,#64748b)", 
    emoji: "📚", 
    pages: 250,
    year: 2020
  },
  { 
    id: "nt-taudhih-2", 
    title: "Taudhîhul Adillah Buku 2 (Ushul & Akhlak)", 
    author: "KH. M. Syafi'i Hadzami", 
    link: "https://drive.google.com/file/d/1WDD-RqMxNxCNSJMYhYh8C5xLNAW-vQpL/view?usp=sharing",
    description: "Membahas tentang dasar-dasar hukum Islam dan pembentukan akhlak.", 
    gradient: "linear-gradient(135deg,#334155,#64748b)", 
    emoji: "📜", 
    pages: 280,
    year: 2020
  },
  { 
    id: "nt-taudhih-3", 
    title: "Taudhîhul Adillah Buku 3 (Thoharah)", 
    author: "KH. M. Syafi'i Hadzami", 
    link: "https://drive.google.com/file/d/1g32a5Fo2nxBStmaweOvyyohIW5OOaNK-/view?usp=sharing",
    description: "Panduan lengkap mengenai tata cara bersuci (Thoharah).", 
    gradient: "linear-gradient(135deg,#334155,#64748b)", 
    emoji: "💧", 
    pages: 230,
    year: 2020
  },
  { 
    id: "nt-taudhih-4", 
    title: "Taudhîhul Adillah Buku 4 (Shalat)", 
    author: "KH. M. Syafi'i Hadzami", 
    link: "https://drive.google.com/file/d/1eFYPtKVJCzjWxY2Jee5_jvNzENoLOYgv/view?usp=sharing",
    description: "Kajian mendalam mengenai dalil-dalil dalam ibadah shalat.", 
    gradient: "linear-gradient(135deg,#334155,#64748b)", 
    emoji: "🕌", 
    pages: 350,
    year: 2020
  },
  { 
    id: "nt-taudhih-5", 
    title: "Taudhîhul Adillah Buku 5 (Puasa-Zakat-Haji)", 
    author: "KH. M. Syafi'i Hadzami", 
    link: "https://drive.google.com/file/d/1PXTkbDK2TeH75PXRbLmXoWsDTKSKxAJ-/view?usp=sharing",
    description: "Panduan dalil tentang Puasa, Zakat, Haji, dan pengurusan Jenazah.", 
    gradient: "linear-gradient(135deg,#334155,#64748b)", 
    emoji: "🕋", 
    pages: 400,
    year: 2020
  },
  { 
    id: "nt-taudhih-6", 
    title: "Taudhîhul Adillah Buku 6 (Muamalah-Nikah)", 
    author: "KH. M. Syafi'i Hadzami", 
    link: "https://drive.google.com/file/d/1ZkGd7dRIq2bTg9BZLYJaD_9zoiJdLP07/view?usp=sharing",
    description: "Penjelasan hukum Islam tentang transaksi dan pernikahan.", 
    gradient: "linear-gradient(135deg,#334155,#64748b)", 
    emoji: "🤝", 
    pages: 380,
    year: 2020
  },

  // --- KATEGORI PENGETAHUAN & ENSIKLOPEDIA ---
  { 
    id: "nt-kematian", 
    title: "Ensiklopedi Kematian & Hari Akhir", 
    author: "Imam Al-Ghazali (Kompilasi)", 
    link: "https://drive.google.com/file/d/16_W9QlsY7jp--iHi-HGO5yUeZE0pbanl/view?usp=sharing",
    description: "Membahas persiapan menghadapi kematian dan gambaran hari akhir.", 
    gradient: "linear-gradient(135deg,#451a03,#92400e)", 
    emoji: "⏳", 
    pages: 310,
    year: 2021
  },
  { 
    id: "nt-pahlawan", 
    title: "Ensiklopedi Pahlawan Nasional", 
    author: "Pustaka Sejarah", 
    link: "https://drive.google.com/file/d/18qAAUjBSV1wpyRf4AghWk4i32Vo5lBNw/view?usp=sharing",
    description: "Mengenal profil dan perjuangan pahlawan-pahlawan bangsa Indonesia.", 
    gradient: "linear-gradient(135deg,#991b1b,#ef4444)", 
    emoji: "🇮🇩", 
    pages: 200,
    year: 2019
  },
  { 
    id: "nt-nabi-25", 
    title: "Kisah 25 Nabi dan Rasul", 
    author: "Tim Literasi Islam", 
    link: "https://drive.google.com/file/d/1we2XwyFrsn8zM_qgZB1auKwX3YSjkmkR/view?usp=sharing",
    description: "Keteladanan hidup para nabi dan rasul Allah dalam berdakwah.", 
    gradient: "linear-gradient(135deg,#fbbf24,#f59e0b)", 
    emoji: "🐫", 
    pages: 180,
    year: 2022
  },
  { 
    id: "nt-abunawas", 
    title: "1001 Malam Abu Nawas", 
    author: "Kisah Klasik", 
    link: "https://drive.google.com/file/d/1DMwuaCRerm8Q7y75P3Iigr6xmhuragWP/view?usp=sharing",
    description: "Kumpulan kisah lucu dan cerdik Abu Nawas yang penuh hikmah.", 
    gradient: "linear-gradient(135deg,#7e22ce,#a855f7)", 
    emoji: "🧞‍♂️", 
    pages: 150,
    year: 2020
  },

  // --- KATEGORI CERITA & DAERAH ---
  { 
    id: "nt-banda", 
    title: "Banda Penghuni Taman", 
    author: "Literasi Nusantara", 
    link: "https://drive.google.com/file/d/10OQvUe-2wG3YQLpJVAlTb8dCafBruu0I/view?usp=sharing",
    description: "Kisah fiksi pengayaan yang mengajarkan tentang menjaga lingkungan.", 
    gradient: "linear-gradient(135deg,#15803d,#22c55e)", 
    emoji: "🌻", 
    pages: 80,
    year: 2021
  },
  { 
    id: "nt-nibung", 
    title: "Putri Nibung di Sarang Lamun", 
    author: "Cerita Rakyat", 
    link: "https://drive.google.com/file/d/18hVfBrr555If_SJvNuQ83FyvS1a3nHCR/view?usp=sharing",
    description: "Cerita rakyat tradisional yang kaya akan pesan moral dan budaya.", 
    gradient: "linear-gradient(135deg,#db2777,#f472b6)", 
    emoji: "👸", 
    pages: 65,
    year: 2019
  },
  { 
    id: "nt-kerongo", 
    title: "Si Kerongo", 
    author: "Dongeng Nusantara", 
    link: "https://drive.google.com/file/d/1uWIAPOiUCbBZNdPxckYsBhA5gFmKIoOf/view?usp=sharing",
    description: "Kisah unik Si Kerongo dalam petualangan yang mendidik.", 
    gradient: "linear-gradient(135deg,#0891b2,#22d3ee)", 
    emoji: "🐢", 
    pages: 50,
    year: 2021
  },
  { 
    id: "st-worms-fishing", 
    title: "Worms for Fishing", 
    author: "Zian Alfiana", 
    link: "https://drive.google.com/file/d/1f0sFATvsu3caZ_1EujIrmnutGR_ysK7c/view?usp=sharing",
    description: "Kisah petualangan mencari cacing untuk memancing. Ilustrasi oleh Naila Nabilatul Husna.", 
    gradient: "linear-gradient(135deg,#fbbf24,#f59e0b)", 
    emoji: "🪱", 
    pages: 20,
    year: 2025,
    ageGroup: "5-9 tahun"
  },
  { 
    id: "st-red-hen", 
    title: "The Little Red Hen", 
    author: "Starfall Education", 
    link: "https://drive.google.com/file/d/16T7oLpl6Px6i6lKqHPuAMJpXCAaHrxE5/view?usp=sharing",
    description: "Kumpulan cerita rakyat klasik termasuk kisah Ayam Betina Merah yang rajin.", 
    gradient: "linear-gradient(135deg,#ef4444,#dc2626)", 
    emoji: "🐔", 
    pages: 48,
    year: 2020,
    ageGroup: "4-7 tahun"
  },
  { 
    id: "st-lantern-girl", 
    title: "The Lantern Girl", 
    author: "Rasya Swarnasta", 
    link: "https://drive.google.com/file/d/10AKeuP8rzg2O5gcOeVIUC4y2rdzLeDvW/view?usp=sharing",
    description: "Cerita menyentuh tentang seorang gadis pembawa lentera. Ilustrasi oleh Kautsar Riina Arifin.", 
    gradient: "linear-gradient(135deg,#6366f1,#4f46e5)", 
    emoji: "🏮", 
    pages: 24,
    year: 2022,
    ageGroup: "6-10 tahun"
  },
  { 
    id: "st-mom-findout", 
    title: "Don’t Let Mom Find Out!", 
    author: "Yuniar Khairani", 
    link: "https://drive.google.com/file/d/1yR3nIDL50KtLksW6O9R453spg5t-pbWm/view?usp=sharing",
    description: "Kisah penuh rahasia dan kelucuan agar ibu tidak mengetahui sesuatu hal.", 
    gradient: "linear-gradient(135deg,#ec4899,#db2777)", 
    emoji: "🤫", 
    pages: 18,
    year: 2025,
    ageGroup: "5-9 tahun"
  },
  { 
    id: "st-finding-kuroki", 
    title: "Finding Kuroki", 
    author: "Heni Prasetyorini", 
    link: "https://drive.google.com/file/d/1mrWRXhW0uxit7NmFG-KYde_taW6Z3_--/view?usp=sharing",
    description: "Petualangan mencari Kuroki. Cerita yang melatih ketelitian dan kasih sayang.", 
    gradient: "linear-gradient(135deg,#10b981,#059669)", 
    emoji: "🔎", 
    pages: 22,
    year: 2025,
    ageGroup: "6-9 tahun"
  },
  { 
    id: "st-strong-mom", 
    title: "Strong Like Mom", 
    author: "Witaru Emi", 
    link: "https://drive.google.com/file/d/1CFkI1g_id1BZIdKCpfoLrWuxLPsB-RvY/view?usp=sharing",
    description: "Cerita inspiratif tentang anak yang ingin menjadi kuat seperti ibunya.", 
    gradient: "linear-gradient(135deg,#f43f5e,#e11d48)", 
    emoji: "💪", 
    pages: 20,
    year: 2022,
    ageGroup: "5-8 tahun"
  },
  { 
    id: "st-magic-hands", 
    title: "Magic Hands", 
    author: "Agem Jaya Dini", 
    link: "https://drive.google.com/file/d/1YqDDz_sLxwDKHnbe_4J-Ox7PTwa2vt70/view?usp=sharing",
    description: "Kekuatan tangan ajaib yang bisa menciptakan banyak hal luar biasa.", 
    gradient: "linear-gradient(135deg,#8b5cf6,#7c3aed)", 
    emoji: "✨", 
    pages: 18,
    year: 2025,
    ageGroup: "4-7 tahun"
  },
  { 
    id: "st-ask-durian", 
    title: "Please Ask for Durian", 
    author: "Pristian Wulanita", 
    link: "https://drive.google.com/file/d/1FnIrmE2HHFeCzlqlx5HIukatHnyPpDYk/view?usp=sharing",
    description: "Cerita unik seputar buah durian yang khas. Ilustrasi menarik oleh Livia Lim.", 
    gradient: "linear-gradient(135deg,#84cc16,#65a30d)", 
    emoji: "🍈", 
    pages: 16,
    year: 2025,
    ageGroup: "6-10 tahun"
  },
  // --- KATEGORI SEJARAH & SIRAH ---
  { 
    id: "nt-sejarah-peradaban-1", 
    title: "Sejarah Peradaban Islam (Prakenabian - Indonesia)", 
    author: "Dr. Din Muhammad Zakariya, M.Pd.I", 
    link: "https://drive.google.com/file/d/1pW6tHJk56r8aRxsRJ26kTp7LAP_bNsc4/view?usp=sharing",
    description: "Membahas perjalanan Islam mulai dari masa pra-kenabian hingga masuknya Islam ke Indonesia.", 
    gradient: "linear-gradient(135deg,#1e293b,#334155)", 
    emoji: "📜", 
    pages: 250, // Estimasi ketebalan buku teks
    year: 2018,
    publisher: "CV. Intrans Publishing – Malang",
    isbn: "978-602-08996-4-0"
  },
  { 
    id: "nt-sejarah-nusantara", 
    title: "Sejarah Islam di Nusantara", 
    author: "Michael Laffan", 
    link: "https://drive.google.com/file/d/1meKaEykLdZsTwUIzsRtWdJmWuL7OWiFT/view?usp=sharing",
    description: "Terjemahan dari 'The Makings of Indonesian Islam'. Analisis mendalam sejarah Islam di wilayah kepulauan.", 
    gradient: "linear-gradient(135deg,#7c2d12,#9a3412)", 
    emoji: "🗺️", 
    pages: 350,
    year: 2015,
    publisher: "Penerbit Bentang (PT Bentang Pustaka)",
    isbn: "-"
  },
  { 
    id: "nt-peradaban-islam-riau", 
    title: "Sejarah Peradaban Islam", 
    author: "Dr. H. Syamruddin Nasution, M.Ag.", 
    link: "https://drive.google.com/file/d/1Zy4_Ze8uGGLcio5v1UVktNWG2wGOSbHX/view?usp=sharing",
    description: "Karya referensi mengenai sejarah peradaban Islam yang diterbitkan oleh Yayasan Pusaka Riau.", 
    gradient: "linear-gradient(135deg,#0f172a,#1e293b)", 
    emoji: "🏛️", 
    pages: 320,
    year: 2013,
    publisher: "Yayasan Pusaka Riau",
    isbn: "979-9339-27-4"
  },
  { 
    id: "nt-sirah-nabawiyah", 
    title: "Sirah Nabawiyah", 
    author: "Tim Penulis", 
    link: "https://drive.google.com/file/d/1Usq4si8T1Rc2I392odW9AX3pRMAa5thP/view?usp=sharing",
    description: "Sejarah lengkap perjalanan hidup dan perjuangan Rasulullah SAW.", 
    gradient: "linear-gradient(135deg,#064e3b,#065f46)", 
    emoji: "✨", 
    pages: 450,
    year: 2020,
    publisher: "Penerbit Umum",
    isbn: "-"
  },
  { 
    id: "nt-bidayah-wan-nihayah", 
    title: "Al-Bidayah Wan Nihayah (Khulafa'ur Rasyidin)", 
    author: "Ibnu Katsir", 
    link: "https://drive.google.com/file/d/1Syu6uArHqrE_U1BWMcn5SZHKp5BUYoYg/view?usp=sharing",
    description: "Kisah sejarah masa kepemimpinan Khulafa'ur Rasyidin dari kitab mahakarya Ibnu Katsir.", 
    gradient: "linear-gradient(135deg,#422006,#713f12)", 
    emoji: "🕋", 
    pages: 600,
    year: 2002,
    publisher: "DARUL HAQ, Jakarta",
    isbn: "-"
  }
];